{{ with .Values.aws_creds }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Release.Name }}-auth
data:
  awskey: {{ if .awskey }}{{ .awskey | b64enc }}{{- else }}''{{- end }}
  awssecret: {{ if .awssecret }}{{ .awssecret | b64enc }}{{- else }}''{{- end }}
  awstoken: {{ if .awstoken }}{{ .awstoken | b64enc }}{{- else }}''{{- end }}
{{- end }}
