version: "3.6"
x-services-volume:
  &shared-workspace
  type: bind
  source: /tmp/cdms.vol
  target: /opt/workspace
services:
  parquet-flask:
    image: parquet-flask
    container_name: parquet-flask
    environment:
      - aws_access_key_id=${aws_access_key_id}
      - aws_secret_access_key=${aws_secret_access_key}
      - aws_session_token=${aws_session_token}
      - parquet_metadata_tbl=cdms_parquet_meta_dev_v1
      - parquet_file_name=s3a://cdms-dev-in-situ-parquet/CDMS_insitu.parquet
      - parquet_file_name_s3=s3a://cdms-dev-in-situ-parquet/CDMS_insitu.parquet
      - parquet_file_name_local=/opt/workspace/CDMS_insitu.parquet
      - master_spark_url_local=spark://spark-master:7077
      - master_spark_bitnami-spark=spark://bitnami-spark-master-svc:7077
      - master_spark=spark://bitnami-spark-master-svc:7077
      - spark_app_name=pyspark-flask
      - log_level=DEBUG
    ports:
      - 9801:9801
    volumes:
      - *shared-workspace
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8478:8888
    volumes:
      - *shared-workspace
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8470:8080
      - 4470:4040
      - 7077:7077
      - 18080:18080
    volumes:
      - *shared-workspace
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3072m
    ports:
      - 8471:8081
    volumes:
      - *shared-workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3072m
    ports:
      - 8472:8081
    volumes:
      - *shared-workspace
    depends_on:
      - spark-master
  spark-worker-3:
    image: spark-worker
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3072m
    ports:
      - 8473:8081
    volumes:
      - *shared-workspace
    depends_on:
      - spark-master
networks:
  internal: